# TrackPay Marketing Site - Netlify Configuration

[build]
  # Publish directory (root since we have static HTML files)
  publish = "."

  # Install dependencies for Netlify Functions
  command = "npm install"

# Netlify Functions Configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Redirect rules
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

# 404 redirect to home
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML cache
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"
